name: Go Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          env:
            CGO_ENABLED: 0
      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o epub-translator-linux-amd64 -ldflags '-extldflags "-static"'
      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o epub-translator-windows-amd64.exe
      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o epub-translator-darwin-amd64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Description of the release
          draft: false
          prerelease: false
      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./epub-translator-linux-amd64
          asset_name: epub-translator-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./epub-translator-windows-amd64.exe
          asset_name: epub-translator-windows-amd64.exe
          asset_content_type: application/octet-stream
      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./epub-translator-darwin-amd64
          asset_name: epub-translator-darwin-amd64
          asset_content_type: application/octet-stream

