name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get dependencies
        run: go mod download

      - name: Build for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o epub-translator-windows-amd64.exe

      - name: Build for Linux (without glibc)
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: go build -o epub-translator-linux-amd64

      - name: Build for macOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o epub-translator-macos-amd64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Windows executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./epub-translator-windows-amd64.exe
          asset_name: epub-translator-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./epub-translator-linux-amd64
          asset_name: epub-translator-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./epub-translator-macos-amd64
          asset_name: epub-translator-macos-amd64
          asset_content_type: application/octet-stream